apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-feed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-feed  # Replace with your deployment name
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization percentage

        
        
      