name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          #- udagram-frontend
          - udagram-api-feed
          - udagram-api-user
          #- udagram-reverseproxy
                

    steps:
    # Runs a single command using the runners shell .
      - name: Run a one-line script
        run: echo Running docker-image for udagram-api-feed.        
      - uses: actions/checkout@v4
      - name: Build and push Docker images                
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      #- name: Find Dockerfile directories
      #  id: find_dockerfiles
      #  run: |
      #    directories=$(find . -type d -name "*Dockerfile*" -print)
      #    echo "directories=$directories" >> $GITHUB_OUTPUT
  
      - name: Build and push
        uses: docker/build-push-action@v6.11.0
        with:
          context: ./${{ matrix.image }}
          file: ./${{ matrix.image }}/Dockerfile
          push: true
          tags: dimahockey/${{ matrix.image }}:latest,dimahockey/${{ matrix.image }}:${{github.run_number}}
          build-args: |            
            POSTGRES_USERNAME_ARG=${{ secrets.POSTGRESUID }}
            POSTGRES_PASSWORD_ARG=${{ secrets.POSTGRESPWD }}
            POSTGRES_HOST_ARG=${{ secrets.POSTGRES_HOST }}
            POSTGRES_DB_ARG=${{ secrets.POSTGRES_DB }}
            AWS_BUCKET_ARG=${{ secrets.AWS_BUCKET }}
            AWS_REGION_ARG=${{ secrets.AWS_REGION }}
            AWS_PROFILE_ARG=${{ secrets.AWS_PROFILE }}
            JWT_SECRET_ARG=${{ secrets.JWT_SECRET }}
            URL_ARG=${{ secrets.URL }}
        
        #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
